2024-08-12 01:31:41 ERROR Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1065, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
ValueError: Sweep wxy-ucas/src-sweep/texas-gat not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/cli/cli.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/cli/cli.py", line 1752, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/wandb_agent.py", line 570, in agent
    return run_agent(
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/wandb_agent.py", line 528, in run_agent
    agent.run()
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/wandb_agent.py", line 190, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/apis/internal.py", line 126, in sweep
    return self.api.sweep(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1065, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
wandb.errors.CommError: Sweep wxy-ucas/src-sweep/texas-gat not found

2024-08-12 01:32:02 ERROR Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1065, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
ValueError: Sweep wxy-ucas/src-sweep/texas-gat not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/cli/cli.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/cli/cli.py", line 1752, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/wandb_agent.py", line 570, in agent
    return run_agent(
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/wandb_agent.py", line 528, in run_agent
    agent.run()
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/wandb_agent.py", line 190, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/apis/internal.py", line 126, in sweep
    return self.api.sweep(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1065, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
wandb.errors.CommError: Sweep wxy-ucas/src-sweep/texas-gat not found

2024-08-12 01:32:19 INFO Running runs: []
2024-08-12 01:32:19 INFO Agent received command: run
2024-08-12 01:32:19 INFO Agent starting run with config:
	XN_activation: False
	alpha_dim: vc
	beta_dim: vc
	data_norm: rw
	dataset: texas
	epoch: 200
	hidden_dim: 128
	m2_mlp: True
	method: rk4
	reaction_term: aggdiff-gat
	self_loop_weight: 1
	step_size: 0.45
	time: 2.45
	use_mlp: False
2024-08-12 01:32:19 INFO About to run command: /usr/bin/env python ../run_GNN_sweep.py --num_splits=10 --wandb --wandb_project=grade-sweep --beta_diag=True --block=constant --use_best_params --XN_activation=False --alpha_dim=vc --beta_dim=vc --data_norm=rw --dataset=texas --epoch=200 --hidden_dim=128 --m2_mlp=True --method=rk4 --reaction_term=aggdiff-gat --self_loop_weight=1 --step_size=0.45 --time=2.45 --use_mlp=False
2024-08-12 01:32:24 INFO Running runs: ['x9s3qmlh']
2024-08-12 01:34:57 INFO Running runs: []
2024-08-12 01:34:57 INFO Agent received command: run
2024-08-12 01:34:57 INFO Agent starting run with config:
	XN_activation: True
	alpha_dim: sc
	beta_dim: vc
	data_norm: rw
	dataset: texas
	epoch: 200
	hidden_dim: 128
	m2_mlp: False
	method: rk4
	reaction_term: aggdiff-gauss
	self_loop_weight: 0
	step_size: 0.15000000000000002
	time: 2.04
	use_mlp: False
2024-08-12 01:34:57 INFO About to run command: /usr/bin/env python ../run_GNN_sweep.py --num_splits=10 --wandb --wandb_project=grade-sweep --beta_diag=True --block=constant --use_best_params --XN_activation=True --alpha_dim=sc --beta_dim=vc --data_norm=rw --dataset=texas --epoch=200 --hidden_dim=128 --m2_mlp=False --method=rk4 --reaction_term=aggdiff-gauss --self_loop_weight=0 --step_size=0.15000000000000002 --time=2.04 --use_mlp=False
2024-08-12 01:35:02 INFO Running runs: ['7jdn62ht']
2024-08-12 01:40:03 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46d4291d00>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/4504800232407040/envelope/
2024-08-12 01:42:14 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46d42e2df0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/4504800232407040/envelope/
2024-08-12 01:43:54 INFO Cleaning up finished run: x9s3qmlh
2024-08-12 01:43:55 INFO Agent received command: run
2024-08-12 01:43:55 INFO Agent starting run with config:
	XN_activation: True
	alpha_dim: sc
	beta_dim: vc
	data_norm: rw
	dataset: texas
	epoch: 200
	hidden_dim: 128
	m2_mlp: False
	method: rk4
	reaction_term: aggdiff-gat
	self_loop_weight: 1
	step_size: 0.30000000000000004
	time: 2.47
	use_mlp: True
2024-08-12 01:43:55 INFO About to run command: /usr/bin/env python ../run_GNN_sweep.py --num_splits=10 --wandb --wandb_project=grade-sweep --beta_diag=True --block=constant --use_best_params --XN_activation=True --alpha_dim=sc --beta_dim=vc --data_norm=rw --dataset=texas --epoch=200 --hidden_dim=128 --m2_mlp=False --method=rk4 --reaction_term=aggdiff-gat --self_loop_weight=1 --step_size=0.30000000000000004 --time=2.47 --use_mlp=True
2024-08-12 01:44:00 INFO Running runs: ['45fldru6']
2024-08-12 01:44:25 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46d42e2d90>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/4504800232407040/envelope/
2024-08-12 01:45:04 INFO Running runs: []
2024-08-12 01:45:05 INFO Agent received command: run
2024-08-12 01:45:05 INFO Agent starting run with config:
	XN_activation: True
	alpha_dim: sc
	beta_dim: vc
	data_norm: gcn
	dataset: texas
	epoch: 200
	hidden_dim: 128
	m2_mlp: False
	method: rk4
	reaction_term: aggdiff-gauss
	self_loop_weight: 1
	step_size: 0.35000000000000003
	time: 2
	use_mlp: False
2024-08-12 01:45:05 INFO About to run command: /usr/bin/env python ../run_GNN_sweep.py --num_splits=10 --wandb --wandb_project=grade-sweep --beta_diag=True --block=constant --use_best_params --XN_activation=True --alpha_dim=sc --beta_dim=vc --data_norm=gcn --dataset=texas --epoch=200 --hidden_dim=128 --m2_mlp=False --method=rk4 --reaction_term=aggdiff-gauss --self_loop_weight=1 --step_size=0.35000000000000003 --time=2 --use_mlp=False
2024-08-12 01:45:10 INFO Running runs: ['d64uvrvx']
2024-08-12 01:46:40 INFO Running runs: []
2024-08-12 01:46:40 INFO Agent received command: run
2024-08-12 01:46:40 INFO Agent starting run with config:
	XN_activation: False
	alpha_dim: sc
	beta_dim: vc
	data_norm: rw
	dataset: texas
	epoch: 200
	hidden_dim: 128
	m2_mlp: False
	method: rk4
	reaction_term: aggdiff-log
	self_loop_weight: 1
	step_size: 0.15000000000000002
	time: 2.04
	use_mlp: True
2024-08-12 01:46:40 INFO About to run command: /usr/bin/env python ../run_GNN_sweep.py --num_splits=10 --wandb --wandb_project=grade-sweep --beta_diag=True --block=constant --use_best_params --XN_activation=False --alpha_dim=sc --beta_dim=vc --data_norm=rw --dataset=texas --epoch=200 --hidden_dim=128 --m2_mlp=False --method=rk4 --reaction_term=aggdiff-log --self_loop_weight=1 --step_size=0.15000000000000002 --time=2.04 --use_mlp=True
2024-08-12 01:46:45 INFO Running runs: ['a6y3qadw']
2024-08-12 01:48:48 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46d42912e0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/4504800232407040/envelope/
2024-08-12 01:50:11 INFO Cleaning up finished run: d64uvrvx
2024-08-12 01:50:13 INFO Agent received command: run
2024-08-12 01:50:13 INFO Agent starting run with config:
	XN_activation: False
	alpha_dim: sc
	beta_dim: sc
	data_norm: rw
	dataset: texas
	epoch: 200
	hidden_dim: 256
	m2_mlp: False
	method: euler
	reaction_term: aggdiff-gauss
	self_loop_weight: 0
	step_size: 0.2
	time: 2.39
	use_mlp: True
2024-08-12 01:50:13 INFO About to run command: /usr/bin/env python ../run_GNN_sweep.py --num_splits=10 --wandb --wandb_project=grade-sweep --beta_diag=True --block=constant --use_best_params --XN_activation=False --alpha_dim=sc --beta_dim=sc --data_norm=rw --dataset=texas --epoch=200 --hidden_dim=256 --m2_mlp=False --method=euler --reaction_term=aggdiff-gauss --self_loop_weight=0 --step_size=0.2 --time=2.39 --use_mlp=True
2024-08-12 01:50:18 INFO Running runs: ['y4ekveri']
2024-08-12 01:50:59 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46d429e1f0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/4504800232407040/envelope/
2024-08-12 01:53:10 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46d429e160>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/4504800232407040/envelope/
2024-08-12 01:54:47 INFO Cleaning up finished run: y4ekveri
2024-08-12 01:54:47 INFO Agent received command: run
2024-08-12 01:54:47 INFO Agent starting run with config:
	XN_activation: False
	alpha_dim: vc
	beta_dim: vc
	data_norm: gcn
	dataset: texas
	epoch: 200
	hidden_dim: 64
	m2_mlp: True
	method: rk4
	reaction_term: aggdiff-gauss
	self_loop_weight: 0
	step_size: 0.30000000000000004
	time: 2.06
	use_mlp: False
2024-08-12 01:54:47 INFO About to run command: /usr/bin/env python ../run_GNN_sweep.py --num_splits=10 --wandb --wandb_project=grade-sweep --beta_diag=True --block=constant --use_best_params --XN_activation=False --alpha_dim=vc --beta_dim=vc --data_norm=gcn --dataset=texas --epoch=200 --hidden_dim=64 --m2_mlp=True --method=rk4 --reaction_term=aggdiff-gauss --self_loop_weight=0 --step_size=0.30000000000000004 --time=2.06 --use_mlp=False
2024-08-12 01:54:52 INFO Running runs: ['xa0g5koh']
2024-08-12 01:56:08 INFO Cleaning up finished run: a6y3qadw
2024-08-12 01:56:09 INFO Agent received command: run
2024-08-12 01:56:09 INFO Agent starting run with config:
	XN_activation: True
	alpha_dim: vc
	beta_dim: vc
	data_norm: rw
	dataset: texas
	epoch: 200
	hidden_dim: 256
	m2_mlp: False
	method: euler
	reaction_term: aggdiff-log
	self_loop_weight: 0
	step_size: 0.5
	time: 2.2
	use_mlp: False
2024-08-12 01:56:09 INFO About to run command: /usr/bin/env python ../run_GNN_sweep.py --num_splits=10 --wandb --wandb_project=grade-sweep --beta_diag=True --block=constant --use_best_params --XN_activation=True --alpha_dim=vc --beta_dim=vc --data_norm=rw --dataset=texas --epoch=200 --hidden_dim=256 --m2_mlp=False --method=euler --reaction_term=aggdiff-log --self_loop_weight=0 --step_size=0.5 --time=2.2 --use_mlp=False
2024-08-12 01:56:14 INFO Running runs: ['0suwm4lu']
